### ISSUE TITLE
KGLM-03 adaptation issues

### ISSUE THREAD

**Issue by LeoD218** [PrintersForAnts/Micron#107]
KGLM-03 is too expensive and difficult to buy, can it be adapted to other bearings?

**Comment by grmocg** [comment]
There is already a non-KGLM-03 option:
 [[a]_z_joint_printed_alternative_x4.stl](https://github.com/PrintersForAnts/Micron/blob/main/STLs/Gantry/Z_Joints/%5Ba%5D_z_joint_printed_alternative_x4.stl)

**Comment by hartk1213** [comment]
> KGLM-03 is too expensive and difficult to buy, can it be adapted to other bearings?

As stated above there is a printed only option.. going to close this issue
