### ISSUE TITLE
Direct access to Micron_CAD_Assembly.step instead of zip file

### ISSUE THREAD

**Issue by izanamisu** [PrintersForAnts/Micron#109]
Hi,

We are using an addon for fusion360 called Voron-Construct ( https://github.com/PrintersForAnts/Voron-Construct)
The addon gives us acces to step files to use in fusion. 

The printer files are ziped and are not available in the addon, can you guys unzip and upload the step files to the cad repositories?

![303910784-1056764f-1323-4dbd-9ccc-3091e439c2e6](https://github.com/PrintersForAnts/Micron/assets/78270523/bde612a7-c22a-4868-8f5d-4d02f28ed7a2)

**Comment by izanamisu** [comment]
PS, Tiny-t and others as well please.

**Comment by izanamisu** [comment]
![image](https://github.com/PrintersForAnts/Micron/assets/78270523/1056764f-1323-4dbd-9ccc-3091e439c2e6)

**Comment by hartk1213** [comment]
not at the moment, it becomes too big of a file at that point , R1 cad is unzipped tho 

ill have to fix the cad file to make it smaller but that most likely wont be until R1 is done

**Comment by THEDUDEDAD** [comment]
> not at the moment, it becomes too big of a file at that point , R1 cad is unzipped tho 
> 
> 
> 
> ill have to fix the cad file to make it smaller but that most likely wont be until R1 is done 
> 
> 
> 
> 

Do you recommend a new builder with a forbot micron kit, to do the r1 gantry or stock ?

**Comment by hartk1213** [comment]
> > not at the moment, it becomes too big of a file at that point , R1 cad is unzipped tho
> > ill have to fix the cad file to make it smaller but that most likely wont be until R1 is done
> 
> Do you recommend a new builder with a forbot micron kit, to do the r1 gantry or stock ?

R1 at this point
