### ISSUE TITLE
Only `z_tensioner_a` inclunded in repo STLs

### ISSUE THREAD

**Issue by DonutCables** [PrintersForAnts/Micron#113]
In the CAD there's `z_tensioner_a` to accompany `z_tensioner_bracket_a`, and likewise for B, but `STLs/Z_Idlers/[a]_z_tensioner_x4.stl` is only the A variant, so unless you know to mirror two of them for printing you have to assemble them opposite of the manual or have slop in the bearings from the screw not tightening properly.

**Comment by TheyCallMeZ** [comment]
Hi @DonutCables I double checked in my slicer and the tensioner piece is universal.  Using some clever rotation I can demonstrate this 
![image](https://github.com/PrintersForAnts/Micron/assets/321143/3e411f8e-c784-43c8-9e25-ca62b08cf70e)

That said I know many people including myself have gone with the [Beefy Z Idlers by clee](https://github.com/clee/VoronBFI/tree/main/STLs/BZI)

**Comment by DonutCables** [comment]
The problem isn't whether they'll fit the other pieces, the issue is one of the screw holes is 3mm to be threaded into and the other is 3.4mm for a through-fit. So when it's four printed the same direction you have to ignore the info in the guide and put two screws for the bearings opposite direction to actually close the piece into the bearings.
And while people may use those files, they're not the most helpful for us getting PIF prints.

**Comment by TheyCallMeZ** [comment]
@DonutCables you are correct. I went ahead and mirrored the stl and fixed the naming, I have also created a PR into the main repo branch. 

I have printed it and the image showing the test fit is on the pull request.

**Comment by hartk1213** [comment]
> The problem isn't whether they'll fit the other pieces, the issue is one of the screw holes is 3mm to be threaded into and the other is 3.4mm for a through-fit. So when it's four printed the same direction you have to ignore the info in the guide and put two screws for the bearings opposite direction to actually close the piece into the bearings. And while people may use those files, they're not the most helpful for us getting PIF prints.

Pif doesn't supply micron files , also R1 micron has better Z idlers that should be used now anyway

**Comment by hartk1213** [comment]
> Hi @DonutCables I double checked in my slicer and the tensioner piece is universal. Using some clever rotation I can demonstrate this ![image](https://private-user-images.githubusercontent.com/321143/319991824-3e411f8e-c784-43c8-9e25-ca62b08cf70e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzk0NTYsIm5iZiI6MTcxMjMzOTE1NiwicGF0aCI6Ii8zMjExNDMvMzE5OTkxODI0LTNlNDExZjhlLWM3ODQtNDNjOC05ZTI1LWNhNjJiMDhjZjcwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxNzQ1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjY0ODlkNWVmZjMwNThhYTQ2YTAxYzAyOGRjMTI0MzI1M2NhOTU4ZDcyNmU1MTRiNTE0NTUwNDI1YTM4OTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P0OXRuWBgUtrr223oXDPsutlyWCcOeBmbtJkfwO_szY)
> 
> That said I know many people including myself have gone with the [Beefy Z Idlers by clee](https://github.com/clee/VoronBFI/tree/main/STLs/BZI)

The files in clees repo need to be updated..R1 has newer BZI files
