### ISSUE TITLE
R1 Klicky dock is a bit too low

### ISSUE THREAD

**Issue by rsletten** [PrintersForAnts/Micron#117]
Using 

[R1 Gantry Dock](https://github.com/PrintersForAnts/Micron/blob/main/R1_Beta/STLs/Gantry/%5Ba%5D_klicky_gantry_dock.stl)
[Dock](https://github.com/tanaes/whopping_Voron_mods/blob/main/pcb_klicky/STLs/dock-front_insert.stl)
[Probe for Dock](https://github.com/tanaes/whopping_Voron_mods/blob/main/pcb_klicky/STLs/probe-heatset.stl)
[X Carriage](https://github.com/chirpy2605/voron/blob/main/general/Alternative_Voron_Mounts/Modified_Mounts/Micron_Pandora/STLs/X_Carriage_MGN9H_Micron_Long.stl)
[X Carriage Klicky PCB mount](https://github.com/PrintersForAnts/Micron/blob/main/R1_Beta/STLs/Gantry/X_Axis/Probes/klicky_probe_pcb_mount_x1.stl)

![IMG_2946](https://github.com/PrintersForAnts/Micron/assets/2594637/19c81cfa-7ea8-4dfb-b10a-ec4f61189b67)

**Comment by hartk1213** [comment]
fixed with https://github.com/PrintersForAnts/Micron/commit/d570fa8b737f0f519dd8379f9a187f71221e1273

**Comment by hartk1213** [comment]
> @hartk1213 not sure if you get notifications from closed issues ^

added to the latest files  👍🏻 
![image](https://github.com/PrintersForAnts/Micron/assets/12398294/094f514d-7ea1-4ed0-bb45-c0f19be1b0e2)
