### ISSUE TITLE
New R1 spool holder foam #R1_beta_issues

### ISSUE THREAD

**Issue by LordKillZone** [PrintersForAnts/Micron#118]
I think R1 new spoolholder is for 1mm foam, i am using 3mm foam and cannot fit this new spoolholder to mine micron.

**Comment by LordKillZone** [comment]
[
![20240506_214712](https://github.com/PrintersForAnts/Micron/assets/65809981/4a57f59f-a6b1-467e-a5e8-43c66a5fef46)
![20240506_214428](https://github.com/PrintersForAnts/Micron/assets/65809981/e8f37902-5aae-4f35-92be-718d5c025eb1)
![20240506_214417](https://github.com/PrintersForAnts/Micron/assets/65809981/703cb88c-ab98-430e-996e-42e321db4fc1)
](url)

**Comment by hartk1213** [comment]
fixed with https://github.com/PrintersForAnts/Micron/commit/d570fa8b737f0f519dd8379f9a187f71221e1273
