### ISSUE TITLE
(R1 Beta) Enhancement/Fix XY joints cad the holes need adjustment for pin & add recesses for MR63-RS bearings

### ISSUE THREAD

**Issue by shawnchr** [PrintersForAnts/Micron#121]
The plastic tweaks when fully tightened with pin inserted in the toothed pulley spot. 
If you could make that version accept MR63-RS 3mm ID x 6mm OD x 2.5mm thick bearings could use a live shaft setup and get away from the awful bearing in the toothed pulleys this would be much better option.

**Comment by hartk1213** [comment]
which toothed pulleys would you want to use on those live shafts? screenshots, images, etc.. would be helpful 
i have looked into this many times and its pretty tight spacing

**Comment by shawnchr** [comment]
https://www.aliexpress.us/item/3256806492847474.html?pdp_npi=4%40dis%21USD%21US%20%246.46%21US%20%246.46%21%21%216.46%216.46%21%402103266e17157193429125986e60a7%2112000038350662170%21sh%21US%213955099750%21&spm=a2g0o.store_pc_allItems_or_groupList.new_all_items_2007521928836.1005006679162226&gatewayAdapt=glo2usa￼
0.99US $ 84% OFF|5pcs/lot, H Type 2GT Timing Pulley for 6mm Wide Belt 16 20 Teeth 3mm 4mm 5mm Bore with Screw Hole| |
aliexpress.us

**Comment by hartk1213** [comment]
CAD is available and at this time I don't plan on making this change
