### ISSUE TITLE
(R1 Beta) Z drives belt alignment issues

### ISSUE THREAD

**Issue by skuep** [PrintersForAnts/Micron#124]
After installing the new Z drives In noticed that the belt is very close to the inside of the belt routing channels in the front idler and rear AB joints (and belt covers). See these photos:

![IMG_20240519_164121](https://github.com/PrintersForAnts/Micron/assets/5630293/81553e9a-aaca-4e08-b4ca-2b116433d318)
![IMG_20240519_164213](https://github.com/PrintersForAnts/Micron/assets/5630293/f62acddf-b570-4caf-8acb-00d264fdf1cb)
![IMG_20240519_161620](https://github.com/PrintersForAnts/Micron/assets/5630293/98aed1a8-fe64-4f62-ba6f-13686c675719)

The belt seems to be too close to the center of the printer on all 4 Z belts. In the Z-drive, the belt is actually very well centered in the slot of the 16T pulley. Its a bit hard to see here, but take my word for it.
![IMG_20240519_164106](https://github.com/PrintersForAnts/Micron/assets/5630293/f9f49b36-528f-4a3c-96cc-0dd170ba41c4)

I switched to CAD and took some measurements, and it seems like there is a difference in Z-belt position compared to the "old" (current) release that would totally explain these differences. See screenshot here, "old" on the left, R1 on the right. Measurement shows the distance from the front face of the front beam to a specific face on the 16T Z-pulley. There is roughly 1mm difference, which is basically what I observed.

![z-drive-r1](https://github.com/PrintersForAnts/Micron/assets/5630293/e0fb42d0-1fbc-4729-af31-c54e3364d9f2)

**Comment by hartk1213** [comment]
ok this was a few things, the gantry was misaligned in the main assembly but the belt was also off by about .5mm (.528mm) to be exact now its perfectly centered in the gantry spots (Idlers/AB Drives)
before
![image](https://github.com/PrintersForAnts/Micron/assets/12398294/ecc2f1a6-5e44-45b5-8ffc-32c75d23863f)
after 
![image](https://github.com/PrintersForAnts/Micron/assets/12398294/90319284-3163-481b-b5f9-ebaa9e51a230)
AB Drives as well 
![image](https://github.com/PrintersForAnts/Micron/assets/12398294/09ed2db0-48e5-4575-b247-885a11213591)

Ill close this with the next push to the repo

**Comment by skuep** [comment]
Nice, thanks a lot! Did you change something in the Z drives with regards to belt alignment?

**Comment by hartk1213** [comment]
Yes, I adjusted the location of the Z belt pulley to get the belts centered up where they should be
