### ISSUE TITLE
(R1 Beta) Z Drive Main body A & B - Chamfer for locating tabs

### ISSUE THREAD

**Issue by cgauvrit** [PrintersForAnts/Micron#126]
R1 Z Drive Main body A & B - would benefit from the chamfer for locating tabs on the other side for printability
Latest STL from the repo was used.

![image](https://github.com/PrintersForAnts/Micron/assets/13075579/38c3af4a-cb1d-43bb-9782-b0602ea727ac)

**Comment by hartk1213** [comment]
Ah good catch...the chamfer that is there is for that reason, they used to print on the other side but changed ..missed that 👍🏼
