### ISSUE TITLE
(R1 Beta) Z A & B  Drives 20mm corner screws struggle to engage with brass inserts

### ISSUE THREAD

**Issue by Foofinator94** [PrintersForAnts/Micron#128]
The 2 off M3 x 20mm screws on  the corners of the Z drives have poor engagement with the brass inserts. 

A combination of screw thread tolerance, printing tolerance of the clamped part height and counterbore overhangs, and brass insert geometry hamper engagement of the threads.

Suggest to either:

- Increase the counterbore depth to expose more threads to engage in the brass insert (~ 0.5-1mm suffice).
- Increase the bore depth of the brass insert hole to allow M3 x 25mm screws to be used instead of M3 x 20.

**Comment by warasilapm** [comment]
+1 I also experienced this during my build this past weekend.
