### ISSUE TITLE
Will there be a G2Z update for the R1 Beta?

### ISSUE THREAD

**Issue by mookie-** [PrintersForAnts/Micron#132]
Hello,

first, thank you very much for your work. I'm pretty excited building the Micron :)
I wanted to know if there will be a G2Z update for the R1 Beta?

**Comment by hartk1213** [comment]
G2Z update for R1 is just a skirt change and those are in the works at the moment...the overall drives won't change

**Comment by mookie-** [comment]
Thank you! If you need a tester, let me know.

**Comment by hartk1213** [comment]
Files were posted in the discord for the latest changes for g2Z for R1 

![image-50.png](https://github.com/user-attachments/assets/8e761e98-e7db-471a-ad5a-14c5d23cca84)
