### ISSUE TITLE
Printed parts

### ISSUE THREAD

**Issue by astur35** [PrintersForAnts/Micron#135]
Good morning, I am starting to do this project because of the good bed size it has, better than the voron 0.2. My problem comes that I can not find anyone to print all the necessary parts, as they do not use nuts and with my resin printer I can not use inserts, I have to use nuts. Do you know anyone in Europe that prints these parts in ASA / ABS? Thank you very much for the great work done in the development of this machine. 

Translated with DeepL.com (free version)

**Comment by hartk1213** [comment]
i dont, but you could look for someone on the discord that might be able to help with that
