### ISSUE TITLE
Missing some STL's for Stealthburner 

### ISSUE THREAD

**Issue by DaveyRance** [PrintersForAnts/Micron#92]
The following STL's seem to be missing for a complete Mini Stealthburner.

https://github.com/VoronDesign/Voron-0/blob/Voron0.2/STLs/Toolheads/Mini_Stealthburner/%5Ba%5D_MiniSB_Motor_Plate_x1.stl
https://github.com/VoronDesign/Voron-0/blob/Voron0.2/STLs/Toolheads/Mini_Stealthburner/Strain_Relief_Spacer_x2.stl
https://github.com/VoronDesign/Voron-0/blob/Voron0.2/STLs/Toolheads/Mini_Stealthburner/Strain_Relief_Body_x1.stl
https://github.com/VoronDesign/Voron-0/blob/Voron0.2/STLs/Toolheads/Mini_Stealthburner/%5Ba%5D_Guidler_x1.stl
https://github.com/VoronDesign/Voron-0/blob/Voron0.2/STLs/Toolheads/Mini_Stealthburner/%5Ba%5D_Latch_x1.stl
https://github.com/VoronDesign/Voron-0/blob/Voron0.2/STLs/Toolheads/Mini_Stealthburner/%5Ba%5D_Shuttle_x1.stl
https://github.com/VoronDesign/Voron-0/blob/Voron0.2/STLs/Toolheads/Mini_Stealthburner/%5Ba%5D_MiniSB_MidBody_x1.stl

This seems to be a repeat of the issue
https://github.com/PrintersForAnts/Micron/issues/49

**Comment by hartk1213** [comment]
Yeah I can get those added soon, I was waiting for v0.2r1 to get released 👍

**Comment by KyleEgan** [comment]
This was resolved with the R1 MiniSB files 👍🏻

**Comment by DaveyRance** [comment]
Looks good. Was there a changelog for what changed with MiniSB R1 as my searching is failing me. (want to figure is it worth re-printing)

**Comment by DaveyRance** [comment]
Incase anyone else is looking from the v0.2R1 Release notes

Toolhead
Mini Stealthburner direct drive and bowden cowling part cooling ducts improved
an issue with the guidler being able to pivot in an undesired direction was addressed by tightening the bolt holes to reduce play
RIDGA support for the bearings that come stock with the ridga kit has been added
